# Copyright 2026 Jayden Aung
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
# Author: Jayden Aung
"""Markdown report generator for VulSentinel triage results."""

import os
from collections import Counter
from datetime import date
from typing import Any


ACTION_ORDER = ["PATCH NOW", "MONITOR", "LOW PRIORITY"]
ACTION_EMOJI = {
    "PATCH NOW": "🔴",
    "MONITOR": "🟡",
    "LOW PRIORITY": "🟢",
}


def _sort_key(finding: dict[str, Any]) -> tuple:
    action = finding.get("recommended_action", "LOW PRIORITY")
    priority = ACTION_ORDER.index(action) if action in ACTION_ORDER else 99
    cvss = finding.get("cvss_score") or 0.0
    return (priority, -cvss)


def generate_report(
    findings: list[dict[str, Any]],
    products: list[str],
    days: int,
    run_date: date | None = None,
    dry_run: bool = False,
) -> str:
    """Build a Markdown patch advisory report.

    Args:
        findings: List of merged CVE + scoring dicts.
        products: Products that were scanned.
        days: Look-back window used.
        run_date: Report date (defaults to today).
        dry_run: If True, adds a dry-run notice.

    Returns:
        Markdown string.
    """
    today = run_date or date.today()
    date_str = today.strftime("%Y-%m-%d")
    sorted_findings = sorted(findings, key=_sort_key)

    counts = Counter(f.get("recommended_action", "MONITOR") for f in findings)
    patch_now = counts.get("PATCH NOW", 0)
    monitor = counts.get("MONITOR", 0)
    low_pri = counts.get("LOW PRIORITY", 0)

    lines: list[str] = []

    # ── Header ──────────────────────────────────────────────────────────────
    lines.append(f"# CVE Patch Advisory — {date_str}")
    lines.append("")
    if dry_run:
        lines.append("> ⚠️ **DRY RUN** — Claude AI scoring was skipped. Showing raw CVE fetch results only.")
        lines.append("")
    lines.append(f"**Scan date:** {date_str}  ")
    lines.append(f"**Look-back window:** {days} day(s)  ")
    lines.append(f"**Products monitored:** {', '.join(products)}  ")
    lines.append(f"**Total CVEs found:** {len(findings)}")
    lines.append("")

    # ── Summary table ────────────────────────────────────────────────────────
    lines.append("## Summary")
    lines.append("")
    lines.append("| Action | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| 🔴 PATCH NOW | {patch_now} |")
    lines.append(f"| 🟡 MONITOR | {monitor} |")
    lines.append(f"| 🟢 LOW PRIORITY | {low_pri} |")
    lines.append("")

    if not findings:
        lines.append("_No CVEs found in the specified time window._")
        return "\n".join(lines)

    # ── Findings by action ───────────────────────────────────────────────────
    lines.append("## Findings")
    lines.append("")

    for action in ACTION_ORDER:
        group = [f for f in sorted_findings if f.get("recommended_action") == action]
        if not group:
            continue

        emoji = ACTION_EMOJI.get(action, "")
        lines.append(f"### {emoji} {action}")
        lines.append("")

        for f in group:
            cve_id = f.get("cve_id", "N/A")
            product = f.get("product", "unknown")
            cvss = f.get("cvss_score")
            cvss_str = f"{cvss:.1f}" if cvss is not None else "N/A"
            exposure = f.get("exposure_score", "N/A")
            relevance = f.get("telco_cnf_relevance", "N/A")
            reason = f.get("reason", "")
            nvd_url = f.get("nvd_url", "")
            published = f.get("published", "")

            lines.append(f"#### [{cve_id}]({nvd_url})")
            lines.append("")
            lines.append(f"| Field | Value |")
            lines.append(f"|-------|-------|")
            lines.append(f"| Product | `{product}` |")
            lines.append(f"| Published | {published} |")
            lines.append(f"| CVSS Score | {cvss_str} |")
            lines.append(f"| Exposure Score | {exposure}/10 |")
            lines.append(f"| Telco/CNF Relevance | {relevance} |")
            lines.append(f"| Recommended Action | **{action}** |")
            lines.append("")
            lines.append(f"> {reason}")
            lines.append("")

    lines.append("---")
    lines.append(f"_Generated by VulSentinel on {date_str}_")
    return "\n".join(lines)


def write_report(content: str, reports_dir: str, run_date: date | None = None) -> str:
    """Write the report to a dated file and return the path.

    Args:
        content: Markdown report string.
        reports_dir: Directory to write to (created if absent).
        run_date: File date (defaults to today).

    Returns:
        Absolute path of the written file.
    """
    today = run_date or date.today()
    os.makedirs(reports_dir, exist_ok=True)
    path = os.path.join(reports_dir, f"{today.strftime('%Y-%m-%d')}.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return os.path.abspath(path)
